name: Publish to Modrinth

on: 
  workflow_dispatch
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - uses: gradle/gradle-build-action@v2.4.2
      with:
        gradle-version: 7.3
    - name: Publish build
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      run: |
        if [ "${{ github.event.sender.login }}" = "OscarPayn" ] || [ "${{ github.event.sender.login }}" = "bconlon1" ]; then
          chmod +x ./gradlew
        
          ./gradlew build

          cd ~/work/The-Aether/The-Aether/build/libs
          echo *
          find . ! -name "aether-1.19.4-1.0.0-beta.6-forge.jar" -type f -exec rm -f {} +
          echo *
          cd ~/work/The-Aether/The-Aether
        
          ./gradlew modrinth
          cd ~/work/The-Aether/The-Aether/build/libs
          echo *
        fi
